"""Read the supplied XLSX as OOXML, without editing the source workbook.
Run from any directory. Generates runtime-safe GDScript data (also exported
with the game), with source workbook and row provenance.
"""
from pathlib import Path
from zipfile import ZipFile
import xml.etree.ElementTree as ET
import json

ROOT = Path(__file__).resolve().parents[2]
SOURCE = 'assets/models/Licencas_Assets/Registro_de_Licencas_Assets_ATUALIZADO.xlsx'
ns = {'m': 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}
entries = []
with ZipFile(ROOT / SOURCE) as archive:
    strings = []
    if 'xl/sharedStrings.xml' in archive.namelist():
        strings = [''.join(t.text or '' for t in node.findall('.//m:t', ns))
                   for node in ET.fromstring(archive.read('xl/sharedStrings.xml'))]
    sheet = ET.fromstring(archive.read('xl/worksheets/sheet1.xml'))
    for row in sheet.findall('.//m:sheetData/m:row', ns):
        cells = {}
        for cell in row:
            value = cell.find('m:v', ns)
            text = value.text or '' if value is not None else ''.join(t.text or '' for t in cell.findall('.//m:t',ns))
            if cell.get('t') == 's': text = strings[int(text)]
            cells[''.join(c for c in cell.get('r') if c.isalpha())] = text
        if not cells.get('A', '').isdigit() or not cells.get('K', '').startswith('https://'):
            continue
        entries.append(dict(id=int(cells['A']), title=cells['B'], author=cells['D'],
                            source=cells['C'], license=cells['E'], url=cells['K'],
                            license_source=cells['L'], row=int(row.get('r'))))
assert len(entries) == 8, 'Review changed source rows before regenerating credits.'
output = '# Generated by build_credits.py; do not invent attribution.\nextends RefCounted\n'
output += 'const SOURCE := '+json.dumps(SOURCE)+'\n'
output += 'const ENTRIES := '+json.dumps(entries,ensure_ascii=False,indent='\t')+'\n'
(ROOT / 'scenes/ui/credit_data.gd').write_text(output,encoding='utf-8')
print(f'Extracted {len(entries)} asset records from workbook rows 5-12.')
