# Generated by build_credits.py; do not invent attribution.
extends RefCounted
const SOURCE := "assets/models/Licencas_Assets/Registro_de_Licencas_Assets_ATUALIZADO.xlsx"
const ENTRIES := [
	{
		"id": 1,
		"title": "Stylized Low Poly Rocks 001",
		"author": "Creative Trio",
		"source": "Sketchfab",
		"license": "Creative Commons CC BY 4.0",
		"url": "https://sketchfab.com/3d-models/stylized-low-poly-rocks-001-606144dcdefa47a9bbaffc71f910a9af",
		"license_source": "https://3dmodelviewer-ct.netlify.app/?modelUrl=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fgendosplace%2F3dviewer%40main%2FRocks_01.fbx&premiumUrl=https://www.fab.com/listings/a6ad0a4e-648f-46c4-ba2f-adc27d8af692",
		"row": 5
	},
	{
		"id": 2,
		"title": "Stylized Low Poly Plants Pack 01",
		"author": "Creative Trio",
		"source": "Sketchfab",
		"license": "Creative Commons CC BY 4.0",
		"url": "https://sketchfab.com/3d-models/stylized-low-poly-plants-pack-01-ac0b55b2d2b84b0c9b4dc9132e788234",
		"license_source": "https://3dmodelviewer-ct.netlify.app/?modelUrl=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fgendosplace%2F3dviewer%40main%2FPlants_01.fbx&premiumUrl=https://www.fab.com/listings/090c94bd-dfdf-4cb1-89b4-b1b2eaf35b11",
		"row": 6
	},
	{
		"id": 3,
		"title": "Stylized Low Poly Plants 02 Pack",
		"author": "Creative Trio",
		"source": "Sketchfab",
		"license": "Creative Commons CC BY 4.0",
		"url": "https://sketchfab.com/3d-models/stylized-low-poly-plants-02-pack-c727487bbe984662882fbf0866039ceb",
		"license_source": "https://3dmodelviewer-ct.netlify.app/?modelUrl=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fgendosplace%2F3dviewer%40main%2FPlants_02_Pack.fbx&premiumUrl=https://www.fab.com/listings/18e198cd-812e-45d0-a4fe-de6cf70701e0",
		"row": 7
	},
	{
		"id": 4,
		"title": "Stylized Low Poly Flowers Pack 01",
		"author": "Creative Trio",
		"source": "Sketchfab",
		"license": "Creative Commons CC BY 4.0",
		"url": "https://sketchfab.com/3d-models/stylized-low-poly-flowers-pack-01-c75f371ee7f94f05a6198a35863363df",
		"license_source": "https://3dmodelviewer-ct.netlify.app/?modelUrl=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fgendosplace%2F3dviewer%40main%2FFlowers_01.fbx&premiumUrl=https://www.fab.com/listings/b49d6396-ad39-46b1-8807-abcf19a8f9d3",
		"row": 8
	},
	{
		"id": 5,
		"title": "Stylized Low Poly Mushrooms Pack 01",
		"author": "Creative Trio",
		"source": "Sketchfab",
		"license": "Creative Commons CC BY 4.0",
		"url": "https://sketchfab.com/3d-models/stylized-low-poly-mushrooms-pack-01-d46fdb73a3c143b88f9747316d3c23a8",
		"license_source": "https://3dmodelviewer-ct.netlify.app/?modelUrl=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fgendosplace%2F3dviewer%40main%2FMushrooms_Pack_01.fbx&premiumUrl=https://www.fab.com/listings/7c28cd3f-631c-4be4-af28-c0066d4b8f95",
		"row": 9
	},
	{
		"id": 6,
		"title": "Stylized lowpoly Trees Pack 01 and 02",
		"author": "Creative Trio",
		"source": "Sketchfab",
		"license": "Creative Commons CC BY 4.0",
		"url": "https://sketchfab.com/3d-models/stylized-lowpoly-trees-pack-01-and-02-21cdbcf0dfe9418fa1987a7a41995a1e",
		"license_source": "Pack 01: https://3dmodelviewer-ct.netlify.app/?modelUrl=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fgendosplace%2F3dviewer%40main%2FTrees_Pack_01.fbx&premiumUrl=https://www.fab.com/listings/3994f45d-4c14-453a-9c50-b4d8cbc425f7\nPack 02: https://3dmodelviewer-ct.netlify.app/?modelUrl=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fgendosplace%2F3dviewer%40main%2FTrees_Pack_02.fbx&premiumUrl=https://www.fab.com/listings/87510a76-3bdd-4b58-94f1-1907ac80cb77",
		"row": 10
	},
	{
		"id": 7,
		"title": "Pirate Kit",
		"author": "Kenney",
		"source": "Kenney",
		"license": "Creative Commons CC0",
		"url": "https://kenney.nl/assets/pirate-kit",
		"license_source": "https://kenney.nl/assets/pirate-kit",
		"row": 11
	},
	{
		"id": 8,
		"title": "Platformer Kit",
		"author": "Kenney",
		"source": "Kenney",
		"license": "Creative Commons CC0",
		"url": "https://kenney.nl/assets/platformer-kit",
		"license_source": "https://kenney.nl/assets/platformer-kit",
		"row": 12
	}
]
